name: saidia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.0.2
  intl: ^0.20.2
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  share_plus: ^12.0.1
  smooth_star_rating_null_safety: ^1.0.4+2
  table_calendar: ^3.2.0
  syncfusion_flutter_charts: ^32.1.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/App_icon_bg.png
    - assets/logos/Icon_only_logo.png
    - assets/logos/logo_word_tp.png
    - assets/logos/rounded_logo_tp.png
    - assets/logos/vertical_with_word.png
    - assets/logos/with_tagline_horizontal.png
    - assets/logos/with_tagline_vertical.png
