// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSKgnpFu2kFdY206XP30Fg_owCEgW91P4',
    appId: '1:157645569808:web:56d956e54056579d4c2f95',
    messagingSenderId: '157645569808',
    projectId: 'saidia-app-e28dd',
    authDomain: 'saidia-app-e28dd.firebaseapp.com',
    storageBucket: 'saidia-app-e28dd.firebasestorage.app',
    measurementId: 'G-2LY427JSWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMmmSnf0-nM1q-rsrMV7wksMdIICLq4W4',
    appId: '1:157645569808:android:83ebc4dfb941b5644c2f95',
    messagingSenderId: '157645569808',
    projectId: 'saidia-app-e28dd',
    storageBucket: 'saidia-app-e28dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKAwkwuRoMp2mriwXq-0p2jmsQeo-OVUM',
    appId: '1:157645569808:ios:963241dbf0224e0c4c2f95',
    messagingSenderId: '157645569808',
    projectId: 'saidia-app-e28dd',
    storageBucket: 'saidia-app-e28dd.firebasestorage.app',
    iosBundleId: 'com.example.saidiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKAwkwuRoMp2mriwXq-0p2jmsQeo-OVUM',
    appId: '1:157645569808:ios:963241dbf0224e0c4c2f95',
    messagingSenderId: '157645569808',
    projectId: 'saidia-app-e28dd',
    storageBucket: 'saidia-app-e28dd.firebasestorage.app',
    iosBundleId: 'com.example.saidiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSKgnpFu2kFdY206XP30Fg_owCEgW91P4',
    appId: '1:157645569808:web:b56a22ad48fb14f04c2f95',
    messagingSenderId: '157645569808',
    projectId: 'saidia-app-e28dd',
    authDomain: 'saidia-app-e28dd.firebaseapp.com',
    storageBucket: 'saidia-app-e28dd.firebasestorage.app',
    measurementId: 'G-62X2GVJDVB',
  );
}
